apiVersion: apps/v1
kind: Deployment
metadata:
  name: kip-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kip-helloworld
  template:
    metadata:
      labels:
        app: kip-helloworld
    spec:
      containers:
      - name: kip-helloworld
        image: microsoft/aci-helloworld
        ports:
        - containerPort: 80
      nodeSelector:
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists